remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"

url: https://lee-kyungho.github.io
baseurl: ""

# Site settings
title: Kyungho Lee
description: "PhD Student in Economics at Yale"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/lee-kyungho

author:
  name: Kyungho Lee
  email: kyungho.lee@yale.edu
