# Site settings
remote_theme: "mmistakes/jekyll-theme-basically-basic"
# remote_theme: "alshedivat/al-folio"
title: "Kyungho Lee"
baseurl: ""
lang: en-US

email: kyungho.lee@yale.edu
url: "https://lee-kyungho.github.io"
logo: /assets/images/Yale_blue.jpg
github_username: lee-kyungho
google_analytics: G-1JDEW6VCJ0
# twitter_username: kh_lee_econ
author:
  name: Kyungho Lee
  picture: /assets/images/IMG_5826.jpg
  # twitter: kh_lee_econ

sass:
  sass_dir: _sass
  
social_links:
  google_scholar: "https://scholar.google.com/citations?user=RIt-l2IAAAAJ&hl=en"

# Build settings
markdown: kramdown
# theme: jekyll-theme-basically-basic
# stylesheet: /_sass/basically-basic.scss
plugins: # previously gems
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
