# Site settings
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
# remote_theme: "alshedivat/al-folio"
title: "Kyungho Lee"
baseurl: ""
lang: en-US

email: kyungho.lee@yale.edu
url: "https://lee-kyungho.github.io"
logo: /assets/images/Yale_blue.jpg
github_username: lee-kyungho
google_analytics: G-1JDEW6VCJ0
author:
  name: Kyungho Lee
  twitter:
  picture: /assets/images/KL_image (1).jpg

# Build settings
markdown: kramdown
# theme: jekyll-theme-basically-basic
# stylesheet: /_sass/basically-basic.scss
plugins: # previously gems
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
